### PR TITLE
update to use new typescript-rest and typescript-rest-swagger

### PR DESCRIPTION
**Pull request by thiagobustamante**

### CODE REVIEW

**Comment by vrudikov** [comment]
@thiagobustamante i think your branch is kinda outdated?

**Comment by vrudikov** [comment]
@thiagobustamante now API is broken

**Comment by vrudikov** [comment]
So you changed `Server.buildServices(this.app, ...controllers);` to `Server.loadServices(this.app, 'controllers/*', __dirname);` and it seems it broke controllers

**Comment by vrudikov** [comment]
Yep. Returned back to `Server.buildServices` and API works

**Comment by thiagobustamante** [comment]
Hi @vrudikov,
The problem is that you renamed the folder ```controllers``` to ```controller```.... and I did not see it during the merge... I created a new PR

**Comment by vrudikov** [comment]
Oops. Got it

**Pull request merged**
